[[bookmark]]
title = "GitHub"
url = "https://github.com"
description = "代码托管平台"
icon = "github"

[[bookmark]]
title = "Rust 程序设计语言"
url = "https://rustwiki.org/zh-CN/book/"
description = "Rust 官方教程中文版"
icon = "https://www.rust-lang.org/logos/rust-logo-32x32.png"

[[bookmark]]
title = "MDN Web Docs"
url = "https://developer.mozilla.org/zh-CN/"
description = "Web 技术文档"
icon = "https://developer.mozilla.org/favicon-48x48.png"

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png"

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png"

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png" 

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png" 

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png" 

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png" 

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png" 

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png" 

[[bookmark]]
title = "哔哩哔哩"
url = "https://www.bilibili.com/"
description = "弹幕网"
icon = "https://developer.mozilla.org/favicon-48x48.png" 